version: '3'

networks:
  dockerapi-dev:
    driver: bridge 
    
services:

  dot_net:
    image: dot_net:latest
    depends_on:
      - "db"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION_STRING: "host=localhost;port=5432;database=sportshop;username=sportshop;password=sportshop"
    networks:
      - dockerapi-dev
    volumes:
      - ./:/app

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "sportshop"
      POSTGRES_PASSWORD: "sportshop"
      POSTGRES_DB: "sportshop"
    networks:
      - dockerapi-dev    
     